import 'package:html_validator/html_validator.dart';
import 'package:http/http.dart';
import 'package:http/testing.dart';
import 'package:test/test.dart';

/// An example of a JSON response generated by an invalid HTML source.
const _mockInvalidJSON = '''
{
  "messages": [
    {
      "type": "error",
      "lastLine": 114,
      "lastColumn": 73,
      "firstColumn": 9,
      "message": "message",
      "hiliteStart": 10,
      "hiliteLength": 65
    }
  ]
}
''';

void main() {
  group("Testing the 'validateHTML' function", () {
    test('Successful validation', () async {
      final client = MockClient((_) async => Response('{"messages":[]}', 200));
      final isValid = await validateHTML(client: client, source: '');

      expect(isValid, isTrue);
    });

    test('Invalid validation', () async {
      final client = MockClient((_) async => Response(_mockInvalidJSON, 200));
      final isValid = await validateHTML(client: client, source: '');

      expect(isValid, isFalse);
    });
  });
}
