name: website_ci

on:
  push:
    branches:
      - main
      - develop

jobs:
  examples:
    strategy:
      matrix:
        folder:
          [
            ".",
            "tool/html_generator",
            "tool/html_validator",
          ]
      fail-fast: true
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          channel: 'master'

      - name: Install Dependencies
        working-directory: ${{ matrix.folder }}
        run: dart pub get

      - name: Format
        working-directory: ${{ matrix.folder }}
        run: dart format --set-exit-if-changed lib test

      - name: Analyze
        working-directory: ${{ matrix.folder }}
        run: dart analyze lib test

      - name: Run tests
        working-directory: ${{ matrix.folder }}
        run: dart test
